/*
 * シナリオ = 遷移表のイベント列。各手順は TRANSITIONS の 1 行をそのまま再生する。
 *   ctx:  モック設定 (Join Match / Create Match の結果)
 *   hostNote / clientNote: その端末が関与しないときに右パネル (現在の状態の下) に出す注記。端末の画面には出さない
 * シナリオの説明はページに出さず、README のシナリオ一覧に書く。
 */

var SCENARIOS = (function () {
  var hostCreates = ['host.friendMatch', 'host.createMatch'];
  var clientJoins = ['client.friendMatch', 'client.enterCode', 'client.joinMatch'];
  // 参加の確認 (ホスト "Friend joined!" / クライアント "Connecting…") → 両者がそろって同期が終わると Ready 画面 (決定 U4)
  var toReady = hostCreates.concat(clientJoins, ['sys.roomSynced']); // Ready 画面まで (6 手順)
  // 決定 (U31 / U36): 両者が Ready を押したら開始。押すと "Confirming…"、届くと押した側は "Waiting for opponent…"、相手側は "Opponent is ready. Are you?"。
  // 2 人目の Ready が届くと "Starting match…" (読み込み)、自動で VS 画面
  var hostReady = ['host.ready', 'sys.readyConfirmed'];
  var clientReady = ['client.ready', 'sys.readyConfirmed'];
  var bothStart = hostReady.concat(clientReady, ['sys.bothStarted']); // ホストが先 (5 手順)
  var clientFirst = clientReady.concat(hostReady, ['sys.bothStarted']); // クライアントが先
  var toGame = ['vs.done', 'game.countdownDone']; // VS 画面 → ゲーム本体のカウントダウン → プレイ開始
  var clientOnly = 'このシナリオではホストは関与しない (ホストの端末は Online Battle のまま)';
  var hostOnly = 'このシナリオではクライアントは関与しない (クライアントの端末は Online Battle のまま)';
  var toMatchEnd = toReady.concat(bothStart, toGame); // 通常対戦でプレイ開始まで (13 手順)
  var toRandomGame = ['host.randomMatch', 'client.randomMatch', 'sys.opponentFound'].concat(toGame); // ランダム対戦でプレイ開始まで (5 手順)

  return [
    { id: '1', title: '通常対戦 (ホストが先に Ready)', diagram: '01',
      steps: toReady.concat(bothStart, toGame) },
    { id: '1b', title: '通常対戦 (クライアントが先に Ready)', diagram: '01',
      steps: toReady.concat(clientFirst, toGame) },
    { id: '2a', title: '待機中にホストが別画面へ → 友だちが入る → 緑の帯をタップして戻る', diagram: '02 (10-07 の決定 U4 / U14 / U16 / U17)',
      steps: hostCreates.concat(['host.back', 'host.back'], clientJoins, ['host.tapToast', 'sys.roomSynced'], bothStart, toGame) },
    { id: '2b', title: '待機中にホストが別画面へ → 放置して期限切れ → 作り直す', diagram: '02 (10-07 の決定 U7 / U10 / U18)',
      steps: hostCreates.concat(['host.back', 'host.back'], clientJoins,
        ['timer.codeExpired', 'host.tapToast', 'host.createMatch', 'client.joinMatch', 'client.enterCode', 'client.joinMatch', 'sys.roomSynced']) },
    { id: '2c', title: 'Ready 画面でホストが ‹ → 友だちが Ready → "Friend is ready!" をタップして戻る', diagram: '02 (10-07 の決定 U1 / U14)',
      steps: toReady.concat(hostReady, ['host.back'], clientReady, ['host.tapToast'], hostReady, ['sys.bothStarted'], toGame) },
    { id: '2d', title: 'ホストの離席中に友だちが抜ける → "Your friend left." を一度 → 入り直す', diagram: '02 (10-07 の決定 U17)',
      steps: toReady.concat(['host.back', 'client.leaveRoom', 'client.dialog.leaveRoom', 'sys.friendLeftShown', 'client.joinMatch', 'host.tapToast', 'sys.roomSynced']) },
    { id: '2e', title: 'ホストの離席中に友だちが切断 → "Reconnecting…" → 20 秒で "Waiting for your friend…"', diagram: '02 / 03 (10-07 の決定 U5 / U19)',
      steps: toReady.concat(['host.back', 'client.disconnect', 'host.back', 'timer.disconnectTimeout', 'client.retry', 'net.recovered', 'host.tapToast', 'sys.roomSynced']) },
    { id: '3a', title: 'Ready 画面でホストが切断 → 20 秒のうちに戻る → もう一度 Ready', diagram: '03 (10-07 の決定 U5 で置き換え)',
      steps: toReady.concat(clientReady, ['host.disconnect', 'net.recovered'], bothStart, toGame) },
    { id: '3b', title: 'Ready 画面でクライアントが切断 → 戻らない → Could not reconnect → Leave Room', diagram: '03 (10-07 の決定 U5 で置き換え)',
      steps: toReady.concat(['client.disconnect', 'timer.disconnectTimeout', 'client.leaveRoom', 'client.dialog.leaveRoom']) },
    { id: '3c', title: 'Ready 画面でホストが切断 → 戻らない → Retry → 空の部屋に戻る', diagram: '03 (10-07 の決定 U5 で置き換え)',
      steps: toReady.concat(['host.disconnect', 'timer.disconnectTimeout', 'host.retry', 'net.recovered', 'client.enterCode', 'client.closeNotice', 'client.joinMatch', 'sys.roomSynced']) },
    { id: '3d', title: '友だちの切断を待っている間にホストが ‹ → "Reconnecting…" の帯 → 戻ってくる', diagram: '03 (10-07 の決定 U14 / U19)',
      steps: toReady.concat(['client.disconnect', 'host.back', 'net.recovered', 'host.tapToast']) },
    { id: '4', title: 'ホストが Close Room (部屋を閉じる)', diagram: '04 (10-07 の決定 U14 / U34 で変更)',
      steps: toReady.concat(['host.closeRoom', 'host.dialog.closeRoom']) },
    { id: '4b', title: 'Close Room の確認で Keep Waiting', diagram: '04 (10-07 の決定 U11 / U14)',
      steps: toReady.concat(hostReady, ['host.closeRoom', 'host.dialog.keepWaiting'], clientReady, ['sys.bothStarted']) },
    { id: '5', title: 'Ready 画面でクライアントが Leave Room → 同じ Match Code で入り直す', diagram: '05 (10-07 の決定 U9 / U34 で変更)',
      steps: toReady.concat(['client.leaveRoom', 'client.dialog.leaveRoom', 'client.joinMatch', 'sys.roomSynced']) },
    { id: '5b', title: '同期の前 ("Connecting…") のクライアントが ‹ → Keep Waiting → Leave Room', diagram: 'なし (10-07 の決定 U9 / U11)',
      steps: hostCreates.concat(clientJoins, ['client.back', 'client.dialog.keepWaiting', 'client.leaveRoom', 'client.dialog.leaveRoom']) },
    { id: '6', title: '読み込みが 20 秒で終わらない → もう一度 Ready', diagram: '06 (10-07 の決定 U32 で変更)',
      steps: toReady.concat(bothStart.slice(0, 4), ['timer.loadTimeout'], bothStart, toGame) },
    { id: '6b', title: '開始の同期に失敗 → もう一度 Ready', diagram: '06 (10-07 の決定 U15 で変更)',
      steps: toReady.concat(bothStart.slice(0, 4), ['sys.syncFailed'], clientFirst, toGame) },
    { id: '7a', title: 'Ready 画面でクライアントが ‹ → 確認 → Keep Waiting → ‹ → 抜ける', diagram: '07 (10-07 の決定 U9 / U35 で置き換え)',
      steps: toReady.concat(clientReady, ['client.back', 'client.dialog.keepWaiting', 'client.back', 'client.dialog.leaveRoom']) },
    { id: '7b', title: 'Ready のあとアプリを離れる → Ready が消える', diagram: '07 (10-07 の決定 U35 で置き換え)',
      steps: toReady.concat(hostReady, ['host.leaveApp'], bothStart, toGame) },
    { id: '8', title: '無効な Match Code', diagram: '08', ctx: { codeResult: 'notFound' }, hostNote: clientOnly,
      steps: clientJoins },
    { id: '9', title: 'Match Code が期限切れ', diagram: '09', ctx: { codeResult: 'expired' }, hostNote: clientOnly,
      steps: clientJoins },
    { id: '10', title: 'マッチが満員', diagram: '10', ctx: { codeResult: 'full' }, hostNote: clientOnly,
      steps: clientJoins },
    { id: '11', title: 'ランダム対戦 (相手が見つかり次第 VS)', diagram: '00 + 10-03 の決定 (U13a)',
      steps: ['host.randomMatch', 'client.randomMatch', 'sys.opponentFound'].concat(toGame) },
    { id: '11b', title: 'ランダム対戦 → Cancel / ‹ で Online Battle へ', diagram: '10-03 / 10-07 の決定 (U13a / U13)', clientNote: hostOnly,
      steps: ['host.randomMatch', 'host.cancelSearch', 'host.randomMatch', 'host.back'] },
    { id: '11c', title: 'ランダム対戦 → アプリを離れて検索が止まる → Search again', diagram: '10-07 の決定 (U13 / U43)',
      steps: ['host.randomMatch', 'host.leaveApp', 'host.searchAgain', 'client.randomMatch', 'sys.opponentFound'] },
    { id: '11d', title: 'ランダム対戦 → アプリを離れて検索が止まる → Close', diagram: '10-07 の決定 (U13 / U43)', hostNote: clientOnly,
      steps: ['client.randomMatch', 'client.leaveApp', 'client.closeNotice'] },
    { id: '11g', title: 'ランダム対戦 → アプリを離れて検索が止まる → 通知を出したまま Friend Match', diagram: '10-07 の決定 (U43)', clientNote: hostOnly,
      steps: ['host.randomMatch', 'host.leaveApp', 'host.friendMatch', 'host.back'] },
    { id: '11e', title: 'ランダム対戦 → 60 秒で見つからない → Search again', diagram: '10-07 の決定 (U13)',
      steps: ['host.randomMatch', 'host.searchTimeout', 'host.searchAgain', 'client.randomMatch', 'sys.opponentFound'] },
    { id: '11f', title: 'ランダム対戦 → 60 秒で見つからない → Close', diagram: '10-07 の決定 (U13)', clientNote: hostOnly,
      steps: ['host.randomMatch', 'host.searchTimeout', 'host.closeNotice'] },
    { id: '12', title: 'VS 画面中にクライアントが切断 → 戻らない → 同じ Match Code で入り直す', diagram: 'なし (10-07 の決定 U32)',
      steps: toReady.concat(bothStart, ['client.disconnect', 'timer.disconnectTimeout', 'client.enterCode', 'client.joinMatch']) },
    { id: '13', title: 'Create / Join がサーバーに届かない (Connection failed)', diagram: '00 (トーストのみ、10-07 の決定 U6)', ctx: { createResult: 'connFailed', codeResult: 'connFailed' },
      steps: hostCreates.concat(clientJoins, ['host.tapToast', 'client.tapToast']) },
    { id: '14', title: '離席中に Create Match → 確認 → 古い部屋は新しい部屋を作れてから閉じる', diagram: 'なし (10-01 合意、10-07 の決定 U12)',
      steps: toReady.concat(['host.back', 'host.createMatch', 'host.dialog.keepCurrent', 'host.createMatch', 'host.dialog.createMatch']) },
    { id: '15', title: 'Friend Match の対戦後 (ホスト勝利 → 両者が抜ける)', diagram: 'なし (10-07 の決定 U20〜U26)',
      steps: toMatchEnd.concat(['host.win', 'host.backToFriendMatch', 'client.backToFriendMatch']) },
    { id: '15b', title: 'Friend Match の対戦後 (時間切れでホストが負け → クライアントが先に抜ける)', diagram: 'なし (10-07 の決定 U20〜U26)',
      steps: toMatchEnd.concat(['host.lose', 'client.backToFriendMatch']) },
    { id: '15c', title: 'Friend Match の再戦 (申し込み → 応じる → VS)', diagram: 'なし (10-07 の決定 U23 / U30)',
      steps: toMatchEnd.concat(['host.win', 'client.rematch', 'host.rematch'], toGame, ['client.win']) },
    { id: '15d', title: '再戦の申し込みを取り消す → 3 秒後にまた申し込める', diagram: 'なし (10-07 の決定 U30)',
      steps: toMatchEnd.concat(['host.win', 'host.rematch', 'host.cancelRematch', 'timer.rematchCooldown', 'client.rematch', 'host.rematch']) },
    { id: '15e', title: '再戦を断られる (Decline)', diagram: 'なし (10-07 の決定 U30)',
      steps: toMatchEnd.concat(['host.win', 'client.rematch', 'host.declineRematch', 'timer.rematchCooldown', 'client.backToFriendMatch']) },
    { id: '15f', title: '再戦の申し込みに応答がない (20 秒) → 申し込み直す', diagram: 'なし (10-07 の決定 U30)',
      steps: toMatchEnd.concat(['host.win', 'host.rematch', 'timer.rematchTimeout', 'timer.rematchCooldown', 'host.rematch', 'client.rematch']) },
    { id: '15g', title: '引き分け → 両者が同時に Rematch', diagram: 'なし (10-07 の決定 U20 / U23)',
      steps: toMatchEnd.concat(['client.draw', 'sys.rematchSimultaneous'], toGame) },
    { id: '15h', title: '結果画面のスタンプとミュート', diagram: 'なし (10-07 の決定 U27)',
      steps: toMatchEnd.concat(['host.win', 'host.stamp.gg', 'client.stamp.thanks', 'host.stampShown', 'client.muteStamps', 'host.stampInterval', 'host.stamp.nice', 'client.unmuteStamps']) },
    { id: '16', title: '対戦中に MATCH MENU → CONTINUE (試合は続く)', diagram: 'なし (10-07 の決定、案A)',
      steps: toMatchEnd.concat(['host.matchMenu', 'client.matchMenu', 'host.matchMenu.continue', 'client.matchMenu.continue']) },
    { id: '16b', title: '対戦中に降参 (SURRENDER → 確認 → 負け)', diagram: 'なし (10-07 の決定、案A)',
      steps: toMatchEnd.concat(['host.matchMenu', 'host.matchMenu.surrender', 'host.surrenderConfirm.continue',
        'host.matchMenu', 'host.matchMenu.surrender', 'host.surrenderConfirm.surrender', 'host.backToOnlineBattle']) },
    { id: '16c', title: 'MATCH MENU を開いている間に試合が終わる', diagram: 'なし (10-07 の決定、案A)',
      steps: toMatchEnd.concat(['host.matchMenu', 'client.win']) },
    { id: '16d', title: 'ランダム対戦で降参 (レートが変わる、再戦なし)', diagram: 'なし (10-07 の決定 U21 / U28 / U41)',
      steps: toRandomGame.concat(['client.matchMenu', 'client.matchMenu.surrender', 'client.surrenderConfirm.surrender', 'host.findNextOpponent', 'client.backToOnlineBattle']) },
    { id: '17', title: 'ランダム対戦の対戦後 (Elo → 再戦はレートが変わらない → 次の相手)', diagram: 'なし (10-07 の決定 U21 / U22 / U29)',
      steps: toRandomGame.concat(['host.win', 'client.rematch', 'host.rematch'], toGame,
        ['client.win', 'host.findNextOpponent', 'client.backToOnlineBattle', 'client.randomMatch', 'sys.opponentFound']) },
    { id: '17b', title: 'ランダム対戦の対戦後 → 次の相手が見つからない', diagram: 'なし (10-07 の決定 U29)',
      steps: toRandomGame.concat(['client.win', 'host.findNextOpponent', 'host.searchTimeout', 'host.searchAgain', 'host.searchTimeout', 'host.backToOnlineBattle']) },
    { id: '17c', title: '次の相手を探している間にアプリを離れる → "Search stopped…" → Search again', diagram: 'なし (10-08 の決定 U47)',
      steps: toRandomGame.concat(['client.win', 'host.findNextOpponent', 'host.leaveApp', 'host.searchAgain', 'client.backToOnlineBattle', 'client.randomMatch', 'sys.opponentFound']) },
    { id: '18', title: '対戦中にクライアントが切断 → 20 秒で切断した側の負け', diagram: 'なし (10-07 の決定 U28)',
      steps: toMatchEnd.concat(['client.disconnect', 'timer.disconnectTimeout', 'host.backToFriendMatch']) },
    { id: '18b', title: '対戦中にホストが切断 → 20 秒のうちに戻る', diagram: 'なし (10-07 の決定 U28)',
      steps: toMatchEnd.concat(['host.disconnect', 'net.recovered', 'host.win']) },
    { id: '18c', title: '両者が切断 → No contest', diagram: 'なし (10-07 の決定 U28)',
      steps: toMatchEnd.concat(['client.disconnect', 'net.bothDisconnected']) },
    { id: '18d', title: 'ランダム対戦でサービス障害 → No contest (レートは変わらない)', diagram: 'なし (10-07 の決定 U28 / U21)',
      steps: toRandomGame.concat(['net.serviceFailure', 'host.backToOnlineBattle', 'client.findNextOpponent']) },
    { id: '18e', title: 'ランダム対戦で切断負け (レートが変わる)', diagram: 'なし (10-07 の決定 U28 / U21)',
      steps: toRandomGame.concat(['host.disconnect', 'timer.disconnectTimeout']) },
    { id: '19', title: 'Cancel Ready (Ready を取り消しても部屋に残る)', diagram: 'なし (10-07 の決定 U34 / U36)',
      steps: toReady.concat(clientReady, ['client.cancelReady'], hostReady) },
    { id: '19b', title: 'Ready のタイムアウト (60 秒)', diagram: 'なし (10-07 の決定 U33)',
      steps: toReady.concat(hostReady, ['timer.readyTimeout'], clientFirst, toGame) },
    { id: '19c', title: 'カウントダウン中にホストが切断 → 20 秒のうちに戻る → もう一度 Ready', diagram: 'なし (10-07 の決定 U32)',
      steps: toReady.concat(bothStart, ['vs.done', 'host.disconnect', 'net.recovered'], bothStart, toGame) },
    { id: '19d', title: 'VS 画面中にホストが切断 → 戻らない → Room closed', diagram: 'なし (10-07 の決定 U32)',
      steps: toReady.concat(bothStart, ['host.disconnect', 'timer.disconnectTimeout']) },
    { id: '19e', title: '友だちの切断を待っている間に Close Room', diagram: 'なし (10-07 の決定 U5 / U14 / U34)',
      steps: toReady.concat(['client.disconnect', 'host.closeRoom', 'host.dialog.closeRoom']) },
    { id: '20', title: '両者が Ready 画面にいる間に期限切れ → Create Match / Join Match', diagram: 'なし (10-07 の決定 U7 / U10 / U18)',
      steps: toReady.concat(clientReady, ['timer.codeExpired', 'host.createMatch', 'client.joinMatch', 'client.enterCode', 'client.joinMatch', 'sys.roomSynced']) },
    { id: '21', title: 'ランダム対戦の VS 画面中に切断 → 20 秒のうちに戻る → VS 画面からやり直す', diagram: 'なし (10-08 の決定 U54)',
      steps: ['host.randomMatch', 'client.randomMatch', 'sys.opponentFound', 'client.disconnect', 'net.recovered'].concat(toGame) },
    { id: '21b', title: 'ランダム対戦のカウントダウン中に切断 → 戻らない → 取りやめ → Search again', diagram: 'なし (10-08 の決定 U52 / U54)',
      steps: ['host.randomMatch', 'client.randomMatch', 'sys.opponentFound', 'vs.done', 'host.disconnect', 'timer.disconnectTimeout', 'host.searchAgain', 'client.searchAgain', 'sys.opponentFound'] },
    { id: '21c', title: 'Friend Match の再戦の VS 画面中に切断 → 戻らない → Friend Match トップ', diagram: 'なし (10-08 の決定 U52 / U54)',
      steps: toMatchEnd.concat(['host.win', 'client.rematch', 'host.rematch', 'client.disconnect', 'timer.disconnectTimeout', 'host.closeNotice', 'client.closeNotice']) },
    // Profile (決定 U56): 変えて保存すると、次に相手を探し始めたときから相手に見える
    { id: '22', title: 'Profile で絵文字とあいさつを変えて Save → ランダム対戦の VS 画面に出る', diagram: 'なし (10-08 の決定 U56)',
      steps: ['host.profile', 'host.pickEmoji.rocket', 'host.pickGreeting.letsSolveThis', 'host.saveProfile'].concat(toRandomGame,
        ['client.win', 'client.muteStamps', 'host.rematch', 'client.rematch']) },
    { id: '22b', title: 'Profile で選んだものを Cancel / ‹ で捨てる', diagram: 'なし (10-08 の決定 U56)', clientNote: hostOnly,
      steps: ['host.profile', 'host.pickEmoji.robot', 'host.pickGreeting.goodLuck', 'host.cancelProfile', 'host.profile', 'host.pickEmoji.star', 'host.back'] },
  ];
})();
